include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: on-failure
    env_file: web.env

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    env_file: db.env
